jobs:
  build:
    if: github.repository == 'apache/drill'
    name: Main Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup java
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Set up swap space
      run: "sudo sh -c \"\n  fallocate -l 4G /tmp/swapfile\n  chmod 0600 /tmp/swapfile\n\
        \  mkswap /tmp/swapfile\n  swapon /tmp/swapfile\n\"\n"
    - continue-on-error: true
      name: Build and test
      run: 'mvn -P${{ matrix.profile }} install --batch-mode --no-transfer-progress
        \

        -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120

        '
    - continue-on-error: true
      name: Remove swap space
      run: "sudo sh -c \"\n  swapoff /tmp/swapfile\n  rm /tmp/swapfile\n\"\n"
    strategy:
      fail-fast: false
      matrix:
        include:
        - java: '8'
          profile: hadoop-2
        java:
        - '8'
        - '11'
        - '17'
        profile:
        - default-hadoop
    timeout-minutes: 150
  checkstyle_protobuf:
    if: github.repository == 'apache/drill'
    name: Run checkstyle and generate protobufs
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup java
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: '8'
    - continue-on-error: true
      name: Cache protobufs
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-protobuf
        path: ~/protobuf
    - continue-on-error: true
      name: Install dependencies
      run: "sudo apt update -y && sudo apt install -y libboost-all-dev libzookeeper-mt-dev\
        \ libsasl2-dev cmake libcppunit-dev checkinstall && \\\npushd .. && \\\nif\
        \ [ -f $HOME/protobuf/protobuf_3.16.3* ]; then \\\n  sudo dpkg -i $HOME/protobuf/protobuf_3.16.3*;\
        \ \\\nelse \\\n  wget https://github.com/protocolbuffers/protobuf/releases/download/v3.16.3/protobuf-java-3.16.3.zip\
        \ && \\\n  unzip protobuf-java-3.16.3.zip && pushd protobuf-3.16.3 && \\\n\
        \  ./configure && sudo make && sudo checkinstall -y && \\\n  if [ ! -d $HOME/protobuf\
        \ ]; then \\\n    mkdir -p $HOME/protobuf; \\\n  fi && \\\n  mv protobuf_3.16.3*\
        \ $HOME/protobuf/ && popd; \\\nfi && \\\nsudo ldconfig && popd; \\\n"
    - continue-on-error: true
      name: Build
      run: 'MAVEN_OPTS="-Xms1G -Xmx1G" mvn install -Drat.skip=false -Dlicense.skip=false
        --batch-mode --no-transfer-progress -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false
        -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        -DskipTests=true -Dmaven.javadoc.skip=true -Dmaven.source.skip=true && \

        pushd protocol && mvn process-sources -P proto-compile && popd && \

        mkdir contrib/native/client/build && pushd contrib/native/client/build &&
        cmake -G "Unix Makefiles" .. && make cpProtobufs && popd; \

        '
    - continue-on-error: true
      name: Check protobufs
      run: "if [ \"$(git status -s | grep -c \"\")\" -gt 0 ]; then \\\n  echo \"The\
        \ following changes are found in files after regenerating protobufs (output\
        \ may be used as a patchto apply):\" >&2 &&\n  echo \"$(git diff --color)\"\
        \ && \\\n  exit 1; \\\nelse\n  echo \"All checks are passed!\";\nfi\n"
name: Github CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
